export const movies = [
  {
    title: "Beyond Earth",
    thumbnail_small: "./assets/thumbnails/beyond-earth/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/beyond-earth/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/beyond-earth/regular/large.jpg",
    year: 2019,
    category: "Movie",
    rating: "PG",
    isBookmarked: false,
    isTrending: true,
  },
  {
    title: "Bottom Gear",
    thumbnail_small: "./assets/thumbnails/bottom-gear/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/bottom-gear/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/bottom-gear/regular/large.jpg",
    year: 2021,
    category: "Movie",
    rating: "PG",
    isBookmarked: false,
    isTrending: true,
  },
  {
    title: "Undiscovered Cities",
    thumbnail_small:
      "./assets/thumbnails/undiscovered-cities/regular/small.jpg",
    thumbnail_medium:
      "./assets/thumbnails/undiscovered-cities/regular/medium.jpg",
    thumbnail_large:
      "./assets/thumbnails/undiscovered-cities/regular/large.jpg",
    year: 2019,
    category: "TV Series",
    rating: "E",
    isBookmarked: false,
    isTrending: true,
  },
  {
    title: "1998",
    thumbnail_small: "./assets/thumbnails/1998/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/1998/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/1998/regular/large.jpg",
    year: 2021,
    category: "Movie",
    rating: "18+",
    isBookmarked: false,
    isTrending: true,
  },
  {
    title: "Dark Side of the Moon",
    thumbnail_small:
      "./assets/thumbnails/dark-side-of-the-moon/regular/small.jpg",
    thumbnail_medium:
      "./assets/thumbnails/dark-side-of-the-moon/trending/small.jpg",
    thumbnail_large:
      "./assets/thumbnails/dark-side-of-the-moon/trending/large.jpg",
    year: 2018,
    category: "TV Series",
    rating: "PG",
    isBookmarked: true,
    isTrending: true,
  },
  {
    title: "The Great Lands",
    thumbnail_small: "./assets/thumbnails/the-great-lands/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/the-great-lands/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/the-great-lands/regular/large.jpg",
    year: 2019,
    category: "Movie",
    rating: "E",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "The Diary",
    thumbnail_small: "./assets/thumbnails/the-diary/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/the-diary/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/the-diary/regular/large.jpg",
    year: 2019,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "Earth’s Untouched",
    thumbnail_small: "./assets/thumbnails/earths-untouched/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/earths-untouched/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/earths-untouched/regular/large.jpg",
    year: 2017,
    category: "Movie",
    rating: "18+",
    isBookmarked: true,
    isTrending: false,
  },
  {
    title: "No Land Beyond",
    thumbnail_small: "./assets/thumbnails/no-land-beyond/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/no-land-beyond/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/no-land-beyond/regular/large.jpg",
    year: 2019,
    category: "Movie",
    rating: "E",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "During the Hunt",
    thumbnail_small: "./assets/thumbnails/during-the-hunt/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/during-the-hunt/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/during-the-hunt/regular/large.jpg",
    year: 2016,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "Autosport the Series",
    thumbnail_small:
      "./assets/thumbnails/autosport-the-series/regular/small.jpg",
    thumbnail_medium:
      "./assets/thumbnails/autosport-the-series/regular/medium.jpg",
    thumbnail_large:
      "./assets/thumbnails/autosport-the-series/regular/large.jpg",
    year: 2016,
    category: "TV Series",
    rating: "18+",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "Same Answer II",
    thumbnail_small: "./assets/thumbnails/same-answer-2/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/same-answer-2/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/same-answer-2/regular/large.jpg",
    year: 2017,
    category: "Movie",
    rating: "E",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "Below Echo",
    thumbnail_small: "./assets/thumbnails/below-echo/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/below-echo/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/below-echo/regular/large.jpg",
    year: 2016,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "The Rockies",
    thumbnail_small: "./assets/thumbnails/the-rockies/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/the-rockies/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/the-rockies/regular/large.jpg",
    year: 2015,
    category: "TV Series",
    rating: "E",
    isBookmarked: true,
    isTrending: false,
  },
  {
    title: "Relentless",
    thumbnail_small: "./assets/thumbnails/relentless/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/relentless/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/relentless/regular/large.jpg",
    year: 2017,
    category: "Movie",
    rating: "PG",
    isBookmarked: true,
    isTrending: false,
  },
  {
    title: "Community of Ours",
    thumbnail_small: "./assets/thumbnails/community-of-ours/regular/small.jpg",
    thumbnail_medium:
      "./assets/thumbnails/community-of-ours/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/community-of-ours/regular/large.jpg",
    year: 2018,
    category: "TV Series",
    rating: "18+",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "Van Life",
    thumbnail_small: "./assets/thumbnails/van-life/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/van-life/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/van-life/regular/large.jpg",
    year: 2015,
    category: "Movie",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "The Heiress",
    thumbnail_small: "./assets/thumbnails/the-heiress/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/the-heiress/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/the-heiress/regular/large.jpg",
    year: 2021,
    category: "Movie",
    rating: "PG",
    isBookmarked: true,
    isTrending: false,
  },
  {
    title: "Off the Track",
    thumbnail_small: "./assets/thumbnails/off-the-track/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/off-the-track/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/off-the-track/regular/large.jpg",
    year: 2017,
    category: "Movie",
    rating: "18+",
    isBookmarked: true,
    isTrending: false,
  },
  {
    title: "Whispering Hill",
    thumbnail_small: "./assets/thumbnails/whispering-hill/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/whispering-hill/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/whispering-hill/regular/large.jpg",
    year: 2017,
    category: "Movie",
    rating: "E",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "112",
    thumbnail_small: "./assets/thumbnails/112/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/112/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/112/regular/large.jpg",
    year: 2013,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "Lone Heart",
    thumbnail_small: "./assets/thumbnails/lone-heart/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/lone-heart/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/lone-heart/regular/large.jpg",
    year: 2017,
    category: "Movie",
    rating: "E",
    isBookmarked: true,
    isTrending: false,
  },
  {
    title: "Production Line",
    thumbnail_small: "./assets/thumbnails/production-line/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/production-line/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/production-line/regular/large.jpg",
    year: 2018,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "Dogs",
    thumbnail_small: "./assets/thumbnails/dogs/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/dogs/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/dogs/regular/large.jpg",
    year: 2016,
    category: "TV Series",
    rating: "E",
    isBookmarked: true,
    isTrending: false,
  },
  {
    title: "Asia in 24 Days",
    thumbnail_small: "./assets/thumbnails/asia-in-24-days/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/asia-in-24-days/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/asia-in-24-days/regular/large.jpg",
    year: 2020,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "The Tasty Tour",
    thumbnail_small: "./assets/thumbnails/the-tasty-tour/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/the-tasty-tour/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/the-tasty-tour/regular/large.jpg",
    year: 2016,
    category: "TV Series",
    rating: "PG",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "Darker",
    thumbnail_small: "./assets/thumbnails/darker/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/darker/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/darker/regular/large.jpg",
    year: 2017,
    category: "Movie",
    rating: "18+",
    isBookmarked: true,
    isTrending: false,
  },
  {
    title: "Unresolved Cases",
    thumbnail_small: "./assets/thumbnails/unresolved-cases/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/unresolved-cases/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/darker/regular/large.jpg",
    year: 2018,
    category: "TV Series",
    rating: "18+",
    isBookmarked: false,
    isTrending: false,
  },
  {
    title: "Mission: Saturn",
    thumbnail_small: "./assets/thumbnails/mission-saturn/regular/small.jpg",
    thumbnail_medium: "./assets/thumbnails/mission-saturn/regular/medium.jpg",
    thumbnail_large: "./assets/thumbnails/mission-saturn/regular/large.jpg",
    year: 2017,
    category: "Movie",
    rating: "PG",
    isBookmarked: true,
    isTrending: false,
  },
];
